export const data = [
  {
    login: "achour_m",
    firstname: "Mohamed-Nour",
    lastname: "ACHOUR",
  },
  {
    login: "ade_o",
    firstname: "Olive",
    lastname: "ADE",
  },
  {
    login: "ambrai_t",
    firstname: "Théo",
    lastname: "AMBRAISSE",
  },
  {
    login: "annerc_a",
    firstname: "Alexis",
    lastname: "ANNERCZOK",
  },
  {
    login: "backek_p",
    firstname: "Pulsy Caleb",
    lastname: "BACKEKOLO",
  },
  {
    login: "baland_h",
    firstname: "Hirche Jaime",
    lastname: "BALANDISSA DIANZINGA",
  },
  {
    login: "bentor_r",
    firstname: "Rayéne",
    lastname: "BEN TORKIA",
  },
  {
    login: "benyou_k",
    firstname: "Khalil",
    lastname: "BEN YOUSSEF",
  },
  {
    login: "boular_t",
    firstname: "Thomas",
    lastname: "BOULARD",
  },
  {
    login: "bousta_a",
    firstname: "Abdelqodousse",
    lastname: "BOUSTANI",
  },
  {
    login: "bouvie_l",
    firstname: "Loic",
    lastname: "BOUVIER",
  },
  {
    login: "bouzia_n",
    firstname: "Nassim Abderaouf",
    lastname: "BOUZIANE",
  },
  {
    login: "brocha_p",
    firstname: "Perrine",
    lastname: "BROCHARD",
  },
  {
    login: "brunet_e",
    firstname: "Ethan",
    lastname: "BRUNET",
  },
  {
    login: "chedda_i",
    firstname: "Iliès",
    lastname: "CHEDDANI",
  },
  {
    login: "chemll_a",
    firstname: "Anass",
    lastname: "CHEMLLAL",
  },
  {
    login: "colak_d",
    firstname: "Devrim",
    lastname: "COLAK",
  },
  {
    login: "deleta_t",
    firstname: "Theo",
    lastname: "DELETANG",
  },
  {
    login: "dichy_s",
    firstname: "Sacha",
    lastname: "DICHY",
  },
  {
    login: "djemba_j",
    firstname: "Junior",
    lastname: "DJEMBA",
  },
  {
    login: "douidi_s",
    firstname: "Sofyan",
    lastname: "DOUIDI",
  },
  {
    login: "ghulam_c",
    firstname: "Chad",
    lastname: "GHULAM",
  },
  {
    login: "haouch_m",
    firstname: "Masthen",
    lastname: "HAOUCHE",
  },
  {
    login: "hoarau_j",
    firstname: "Jordan",
    lastname: "HOARAU",
  },
  {
    login: "issang_b",
    firstname: "Beviryon",
    lastname: "ISSANGA NGOULOU",
  },
  {
    login: "kasmi_b",
    firstname: "Basma",
    lastname: "KASMI",
  },
  {
    login: "luseva_n",
    firstname: "Noah",
    lastname: "LUSEVA",
  },
  {
    login: "manico_y",
    firstname: "Yannis",
    lastname: "MANICORD",
  },
  {
    login: "menut_p",
    firstname: "Paul",
    lastname: "MENUT",
  },
  {
    login: "moad_a",
    firstname: "Abdel",
    lastname: "MOAD",
  },
  {
    login: "montei_j",
    firstname: "Joao Pedro",
    lastname: "MONTEIRO DA SILVA",
  },
  {
    login: "mouham_a",
    firstname: "Ayoub",
    lastname: "MOUHAMAD",
  },
  {
    login: "nkodia_f",
    firstname: "Frid Ricardo",
    lastname: "N KODIA",
  },
  {
    login: "ouabbo_o",
    firstname: "Osman",
    lastname: "OUABBOU",
  },
  {
    login: "ourlis_s",
    firstname: "Slim",
    lastname: "OURLISSENE",
  },
  {
    login: "penich_r",
    firstname: "Rémy",
    lastname: "PENICHON",
  },
  {
    login: "pereir_l",
    firstname: "Laurine",
    lastname: "PEREIRA",
  },
  {
    login: "plafor_d",
    firstname: "Diego",
    lastname: "PLA FORTEA",
  },
  {
    login: "plassa_r",
    firstname: "Raphaël",
    lastname: "PLASSART",
  },
  {
    login: "quinch_e",
    firstname: "Evan",
    lastname: "QUINCHON",
  },
  {
    login: "ramian_i",
    firstname: "Ioahn Mirija",
    lastname: "RAMIANDRASOA RATSIMBA",
  },
  {
    login: "reix_m",
    firstname: "Martin",
    lastname: "REIX",
  },
  {
    login: "retibi_i",
    firstname: "Imed",
    lastname: "RETIBI",
  },
  {
    login: "rincla_r",
    firstname: "Reginord",
    lastname: "RINCLA",
  },
  {
    login: "sargen_a",
    firstname: "Anthony",
    lastname: "SARGENTO",
  },
  {
    login: "schobe_c",
    firstname: "Clément",
    lastname: "SCHOBERT",
  },
  {
    login: "tchiam_m",
    firstname: "Miveck",
    lastname: "TCHIAMA",
  },
  {
    login: "teixei_t",
    firstname: "Thomas",
    lastname: "TEIXEIRA",
  },
  {
    login: "titouc_m",
    firstname: "Maya",
    lastname: "TITOUCHE",
  },
  {
    login: "trak_a",
    firstname: "Amal",
    lastname: "TRAK",
  },
  {
    login: "vignis_h",
    firstname: "Hervanice",
    lastname: "VIGNISSI",
  },
];

const prom = [
  {
    2018: [
      {
        id: 194,
        target_name: "ETNA Online",
        term_name: "ETNA Online",
        learning_start: "2016-01-01",
        learning_end: "2042-01-01",
        learning_duration: 0,
        promo: "2018",
        spe: "",
        wall_name: "ETNA Online - 2018",
      },
    ],
    2023: [
      {
        id: 673,
        target_name: "Architecte logiciel, développeur d'application",
        term_name: "Master - Mars",
        learning_start: "2021-03-29",
        learning_end: "2023-03-03",
        learning_duration: 1297,
        promo: "2023",
        spe: "IDV",
        wall_name: "Master - Mars - 2023",
      },
      {
        id: 676,
        target_name: "Architecte système, réseau et sécurité",
        term_name: "Master - Mars",
        learning_start: "2021-03-29",
        learning_end: "2023-03-03",
        learning_duration: 1297,
        promo: "2023",
        spe: "ISR",
        wall_name: "Master - Mars - 2023",
      },
      {
        id: 721,
        target_name: "Architecte logiciel, développeur d'application",
        term_name: "Master - Octobre",
        learning_start: "2022-02-07",
        learning_end: "2023-10-13",
        learning_duration: 1080,
        promo: "2023",
        spe: "IDV",
        wall_name: "Master - Octobre - 2023",
      },
      {
        id: 724,
        target_name: "Architecte en ingénierie système et réseau",
        term_name: "Master - Octobre",
        learning_start: "2022-02-07",
        learning_end: "2023-10-13",
        learning_duration: 1080,
        promo: "2023",
        spe: "ISR",
        wall_name: "Master - Octobre - 2023",
      },
      {
        id: 154,
        target_name: "Architecte logiciel, développeur d'application",
        term_name: "VAE",
        learning_start: "2022-10-22",
        learning_end: "2023-10-22",
        learning_duration: 0,
        promo: "2023",
        spe: "IDV",
        wall_name: "VAE - 2023",
      },
      {
        id: 155,
        target_name: "Architecte système, réseau et sécurité",
        term_name: "VAE",
        learning_start: "2022-10-22",
        learning_end: "2023-10-22",
        learning_duration: 0,
        promo: "2023",
        spe: "ISR",
        wall_name: "VAE - 2023",
      },
    ],
    2024: [
      {
        id: 703,
        target_name: "Responsable de projet web et mobile",
        term_name: "Bachelor - Octobre",
        learning_start: "2022-02-07",
        learning_end: "2023-01-20",
        learning_duration: 455,
        promo: "2024",
        spe: "",
        wall_name: "Bachelor - Octobre - 2024",
      },
      {
        id: 758,
        target_name: "Architecte logiciel, développeur d'application",
        term_name: "Master - Mars",
        learning_start: "2022-06-20",
        learning_end: "2024-03-08",
        learning_duration: 1115,
        promo: "2024",
        spe: "IDV",
        wall_name: "Master - Mars - 2024",
      },
      {
        id: 761,
        target_name: "Architecte en Ingéniérie Système Réseau",
        term_name: "Master - Mars",
        learning_start: "2022-06-20",
        learning_end: "2024-03-08",
        learning_duration: 1115,
        promo: "2024",
        spe: "ISR",
        wall_name: "Master - Mars - 2024",
      },
      {
        id: 808,
        target_name: "Concepteur.rice de projets SI",
        term_name: "C2WK Master - Octobre",
        learning_start: "2022-10-10",
        learning_end: "2023-01-20",
        learning_duration: 200,
        promo: "2024",
        spe: "",
        wall_name: "C2WK Master - Octobre - 2024",
      },
    ],
    2025: [
      {
        id: 743,
        target_name: "Intégrateur développeur web",
        term_name: "AP2B - Septembre",
        learning_start: "2022-06-20",
        learning_end: "2023-01-27",
        learning_duration: 315,
        promo: "2025",
        spe: "",
        wall_name: "AP2B - Septembre - 2025",
      },
      {
        id: 755,
        target_name: "Responsable de projet web et mobile",
        term_name: "Bachelor - Mars",
        learning_start: "2022-06-20",
        learning_end: "2023-03-24",
        learning_duration: 490,
        promo: "2025",
        spe: "",
        wall_name: "Bachelor - Mars - 2025",
      },
      {
        id: 807,
        target_name: "Concepteur.rice de projets SI",
        term_name: "C2WK Bachelor - Octobre",
        learning_start: "2022-10-10",
        learning_end: "2023-01-27",
        learning_duration: 200,
        promo: "2025",
        spe: "",
        wall_name: "C2WK Bachelor - Octobre - 2025",
      },
      {
        id: 826,
        target_name: "Prérentrée",
        term_name: "Prérentrée - Master",
        learning_start: "2022-10-10",
        learning_end: "2023-10-08",
        learning_duration: 0,
        promo: "2025",
        spe: "",
        wall_name: "Prérentrée - Master - 2025",
      },
    ],
    2026: [
      {
        id: 812,
        target_name: "Intégrateur.rice - développeur.se web",
        term_name: "APE",
        learning_start: "2022-09-19",
        learning_end: "2024-01-26",
        learning_duration: 1505,
        promo: "2026",
        spe: "",
        wall_name: "APE - 2026",
      },
      {
        id: 813,
        target_name: "Intégrateur.rice - développeur.se web",
        term_name: "APAE",
        learning_start: "2022-09-19",
        learning_end: "2024-01-26",
        learning_duration: 1263,
        promo: "2026",
        spe: "",
        wall_name: "APAE - 2026",
      },
      {
        id: 825,
        target_name: "Prérentrée",
        term_name: "Prérentrée - Bachelor",
        learning_start: "2022-10-11",
        learning_end: "2023-10-08",
        learning_duration: 0,
        promo: "2026",
        spe: "",
        wall_name: "Prérentrée - Bachelor - 2026",
      },
    ],
    2027: [
      {
        id: 823,
        target_name: "Prérentrée",
        term_name: "Prérentrée - APE",
        learning_start: "2022-10-11",
        learning_end: "2023-09-17",
        learning_duration: 0,
        promo: "2027",
        spe: "",
        wall_name: "Prérentrée - APE - 2027",
      },
      {
        id: 824,
        target_name: "Prérentrée",
        term_name: "Prérentrée - APAE",
        learning_start: "2022-10-11",
        learning_end: "2023-09-17",
        learning_duration: 0,
        promo: "2027",
        spe: "",
        wall_name: "Prérentrée - APAE - 2027",
      },
    ],
  },
];

export default data;
